name: 'yuzu'
run-name: 'Build yuzu'

on:
  workflow_dispatch:

jobs:
  build-msvc:
    name: 'build (windows, msvc)'

    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          repository: yuzu-emu/yuzu
          submodules: recursive
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.email "yuzu@yuzu-emu.org"
          git config --global user.name "yuzubot"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
      - name: Install dependencies
        # due to how chocolatey works, only cmd.exe is supported here
        shell: cmd
        run: |
          choco install vulkan-sdk
          call refreshenv
          echo %PATH% >> %GITHUB_PATH%
      - name: Merge PR
        uses: actions/github-script@v6
        with: 
          script: |
            const myExec = async (command) => await exec.getExecOutput('"C:\\Program Files\\Git\\bin\\bash.exe"',["-c",command],{silent: true}).then(result => result.stdout.trim()).catch(err => {console.log(err) ; return false })
            const prs = await github.rest.search.issuesAndPullRequests({
              q: "type:pr+is:open+repo:yuzu-emu/yuzu+label:early-access-merge,mainline-merge",
              sort: "updated",
              order: "asc",
              per_page: 100
            }).then(res => res.data.items);
            for (const pr of prs) {
              console.log(`Merge "${pr.title}" ${pr.pull_request.html_url}`);
              let pn = pr.number;
              await myExec(`git fetch "https://github.com/yuzu-emu/yuzu.git" "pull/${pn}/head:pr-${pn}" -f --no-recurse-submodules`);
              await myExec(`git merge --squash "pr-${pn}"`)
              await myExec(`git commit -m "${pr.title}" `)
            };
            let body = await myExec(`GIT_BRANCH=$(git name-rev --name-only HEAD) && git log origin/$GIT_BRANCH..$GIT_BRANCH --pretty=format:"%s"`)
            core.exportVariable("body",body);
            core.exportVariable("time",new Date().toISOString().slice(0,16))
      - name: Pack 7z
        shell: cmd
        run:
          7z a -m0=lzma2 -mx=9 -ms=on yuzu-windows.7z *
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: fullsrc
          path: ./yuzu-windows.7z
          retention-days: 1
